import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request) {
  try {
    const { studentEmail, studentName, score, totalMarks, orgName, examTitle } = await request.json();

    const percentage = ((score / totalMarks) * 100).toFixed(0);

    // Beautiful HTML Email Template with PROMINENT Org Name
    const htmlContent = `
      <div style="font-family: sans-serif; max-w: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
        
        <div style="background-color: #4f46e5; padding: 40px 30px; text-align: center;">
          <p style="color: #c7d2fe; margin: 0 0 10px 0; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;">${orgName}</p>
          <h1 style="color: white; margin: 0; font-size: 28px;">Exam Results Ready</h1>
          <p style="color: #e0e7ff; margin-top: 10px; font-size: 16px;">${examTitle}</p>
        </div>

        <div style="padding: 30px; background-color: #ffffff;">
          <h2 style="color: #1e293b; margin-top: 0;">Hello ${studentName},</h2>
          <p style="color: #475569; font-size: 16px; line-height: 1.5;">
            Thank you for completing your assessment with <strong>${orgName}</strong>. Your final scorecard has been securely generated by our system.
          </p>
          
          <div style="background-color: #f8fafc; border-radius: 12px; padding: 30px 20px; margin: 30px 0; text-align: center; border: 1px solid #e2e8f0;">
            <p style="font-size: 13px; color: #64748b; text-transform: uppercase; letter-spacing: 1.5px; margin: 0 0 10px 0; font-weight: bold;">Final Score</p>
            <h1 style="font-size: 56px; color: #0f172a; margin: 0; line-height: 1;">${score} <span style="font-size: 24px; color: #94a3b8;">/ ${totalMarks}</span></h1>
            
            <div style="display: inline-block; margin-top: 15px; padding: 5px 15px; border-radius: 20px; background-color: ${percentage >= 50 ? '#d1fae5' : '#ffe4e6'}; color: ${percentage >= 50 ? '#059669' : '#e11d48'}; font-weight: bold; font-size: 14px;">
              Accuracy: ${percentage}%
            </div>
          </div>

          <p style="color: #475569; font-size: 14px;">If you have any questions about your performance, please reach out directly to the <strong>${orgName}</strong> support team.</p>
        </div>

        <div style="background-color: #f1f5f9; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
          <p style="color: #64748b; font-size: 12px; margin: 0; font-weight: bold;">${orgName}</p>
          <p style="color: #94a3b8; font-size: 11px; margin: 5px 0 0 0;">Powered securely by OZONE Enterprise</p>
        </div>
      </div>
    `;

    await resend.emails.send({
      from: "Exams <onboarding@resend.dev>", // NOTE: Change this when you verify your own domain!
      to: [studentEmail],
      subject: `Your Results from ${orgName}: ${examTitle}`,
      html: htmlContent,
    });

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error) {
    console.error("Email Error:", error);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}